--- 
- name: "update apt packages"
  become: true
  apt: 
    update_cache: yes

- name: "update packages"
  become: true
  apt: 
    upgrade: yes

- name: "install npm and nodejs"
  become: true
  apt:
    name: ["npm", "nodejs"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes

- name: "Create web directory"
  become: true
  file:
    path: ~/web
    state: directory

- name: "copy index test page to created directory"
  template:
    src: "files/index.js"
    dest: "~/web/index.js"

- name: "Start the web server"
  shell: |
    pm2 start ~/web/index.js -f